version: "3"

services:
  shopware:
    image: dockware/dev:latest
    container_name: shopware
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "3306:3306"
      - "2222:22"
      - "8888:8888"
      - "9999:9999"
      - "9998:9998"
    networks:
      - web
    environment:
      - XDEBUG_ENABLED=1

## ***********************************************************************
##  NETWORKS
## ***********************************************************************
networks:
  web:
    external: false
